
```{r fig.width=10, fig.height=7}
obs <- DGS(simu.num, n=10000) 
print(summary(obs))
  
# check positivity violations
cat("Summary of A given W < -1:")
summary(obs$A[obs$W < -1])
cat("Summary of A given -1 < W <= 0:")
summary(obs$A[-1 <= obs$W & obs$W < 0])
cat("Summary of A given 0 < W <= 1:")
summary(obs$A[0 <= obs$W & obs$W < 1])
cat("Summary of A given 1 < W:")
summary(obs$A[1 <= obs$W])


p1 = ggplot(obs, aes(W)) + geom_histogram(stat="bin",aes(y=..density..), color='lightyellow', fill='lightyellow') + geom_density(lwd=1) + theme_bw() + labs(y='Density')
p2 = ggplot(obs, aes(A)) + geom_histogram(stat="bin",aes(y=..density..), color='lightyellow', fill='lightyellow') + geom_density(lwd=1) + theme_bw() + labs(y='Density')
p3 = ggplot(obs %>% group_by(Y) %>% summarise(count = n()) %>% mutate(Proportion = count / 10000), 
            aes(x = Y, y = Proportion)) + geom_bar(stat = "identity", fill='lightyellow', color='grey') + theme_bw()
p4 = ggplot(obs, aes(W, A)) + geom_point() + theme_bw()
p5 = ggplot(obs, aes(W, Y)) + geom_point() + theme_bw()
p6 = ggplot(obs, aes(A, Y)) + geom_point() + theme_bw()

p <- grid.arrange(p1, p2, p3, p4, p5, p6, 
                  nrow=2, ncol=3,
                  top = textGrob(sprintf('Variable distributions of simulation %i', simu.num), 
                                   gp=gpar(fontsize=17)))
ggsave(here(getwd(), "plots", paste0("simu_sys", simu.num, "_EDAs.png")), p, width = 10, height = 6, dpi = 1000)
```


```{r fig.width=5, fig.height=4}
load(file=here("data", "rdata", paste0("simu_", simu.num ,"_psi0.RData")))

if(simu.num == 4){
  psi0_all_0 = psi0_all[psi0_all$a < 2,]
  psi0_all_1 = psi0_all[psi0_all$a >= 2 & psi0_all$a < 4,]
  psi0_all_0_ = psi0_all[psi0_all$a >= 4,]
  
  ggplot() +
      geom_line(data=psi0_all_0, aes(x=a, y=psi0)) + 
      geom_line(data=psi0_all_1, aes(x=a, y=psi0)) + 
      geom_line(data=psi0_all_0_, aes(x=a, y=psi0)) + 
      geom_point(data=psi0_pnt, aes(x=a, y=psi0)) + 
      geom_point(aes(x = 2, y = psi0_all$psi0[psi0_all$a == max(psi0_all$a[psi0_all$a < 2])]), shape=1) + 
      geom_point(aes(x = 4, y = psi0_all$psi0[psi0_all$a == max(psi0_all$a[psi0_all$a < 4])]), shape=1) + 
      ylim(0,1) +
      labs(x="Treatment", y="Outcome",
           title = "Causal Dose–Response Curve") +
          theme(plot.title = element_text(hjust = 0.5),
                panel.grid.major.x = element_blank(),
                axis.text = element_text(size=7)) +
    theme_bw()
} else {
  ggplot() +
    geom_line(data=psi0_all, aes(x=a, y=psi0)) + 
    geom_point(data=psi0_pnt, aes(x=a, y=psi0)) + 
    ylim(0,1) +
    labs(x="Treatment", y="Outcome",
           title = "Causal Dose–Response Curve") +
        theme(plot.title = element_text(hjust = 0.5),
              panel.grid.major.x = element_blank(),
              axis.text = element_text(size=7)) +
  theme_bw()

}

ggsave(here(getwd(), "plots", paste0("simu_sys", simu.num, "_psi0.png")),  width = 5, height = 4, dpi = 1000)
```


## n = 200
```{r}
nn=200
```

```{r child = 'Simu_results_template_one_simu_one_n.Rmd'}
```


## n = 500
```{r}
nn=500
```

```{r child = 'Simu_results_template_one_simu_one_n.Rmd'}
```



## n = 1000
```{r}
nn=1000
```

```{r child = 'Simu_results_template_one_simu_one_n.Rmd'}
```

<!-- ## n = 5000 -->
<!-- ```{r} -->
<!-- nn=5000 -->
<!-- ``` -->

<!-- ```{r child = 'Simu_results_template_one_simu_one_n.Rmd'} -->
<!-- ``` -->


